#!/usr/bin/env bash
# Inventory the queries that fail when mysqli error reporting is on.
#
# The app fires ~1300 queries and checks almost none of them. PHP 8.1 made
# mysqli throw on error, and connect.php turns that back off with
# MYSQLI_REPORT_OFF, because under exceptions each never-succeeding query
# becomes a fatal -- a behaviour change, not a port. See docs/porting-notes.md.
#
# That decision is correct and it is also a blindfold: nobody knows which
# queries have been failing, or since when. This script takes the blindfold off
# for one run. It restarts the stack with MB_REPORT_QUERIES=1, which selects
# MYSQLI_REPORT_ERROR *without* MYSQLI_REPORT_STRICT -- failures are reported as
# warnings rather than exceptions, so each one names itself and its line and the
# request still completes.
#
# Two surfaces, because they fail in different ways and neither covers the other:
#
#   1. The smoke crawl, in audit mode (MB_QUERY_AUDIT=1), which collects the
#      mysqli warnings instead of failing on them.
#   2. update.php, the game tick, which the crawl never touches -- it is not
#      linked from any page and runs with a different CWD. It is also the
#      densest query surface in the codebase.
#
#   bash tests/query-audit.sh
#
# Not part of run-all.sh: it restarts the container twice, and with reporting on
# the crawl is red by construction. Run it by hand when you want the worklist.
#
# The inventory only covers what these two passes reach -- see $UNREACHABLE in
# smoke.php. It is a floor on the number of broken queries, not a total.
#
# Restores the stack to its normal setting on the way out, including on failure.

set -uo pipefail
cd "$(dirname "$0")/.."
export MSYS_NO_PATHCONV=1

OUT=tests/broken-queries.txt
raw=$(mktemp)

cleanup() {
  rm -f "$raw"
  echo
  echo "Restoring the stack to MB_REPORT_QUERIES=0..."
  MB_REPORT_QUERIES=0 docker compose up -d web > /dev/null 2>&1
}
trap cleanup EXIT

echo "Restarting web with MB_REPORT_QUERIES=1..."
if ! MB_REPORT_QUERIES=1 docker compose up -d web > /dev/null 2>&1; then
  echo "FAIL: could not restart the web container." >&2
  exit 2
fi

# Both passes are destructive -- many actions in this app are plain GET links,
# and the tick rewrites every user -- so each starts from the fixture world.
echo
echo "=== pass 1: the crawl ==="
bash tests/reset-db.sh > /dev/null
docker compose exec -T -e MB_QUERY_AUDIT=1 web php /repo/tests/smoke.php 2>/dev/null \
  | grep '^QUERYFAIL' \
  | cut -f2,3 \
  | awk -F'\t' '{printf "%s\t(seen at: %s)\n", $1, $2}' >> "$raw"
echo "collected $(wc -l < "$raw" | tr -d ' ') failure(s)."

echo
echo "=== pass 2: the tick ==="
bash tests/reset-db.sh > /dev/null
# Normalised into the same "file:line | Warning: message" shape smoke.php's
# signature() produces, so both passes land in one sorted list. The tick logs to
# stderr and echoes to stdout, and PHP writes each warning to both -- hence the
# sort -u further down.
docker compose exec -T -e MB_REPORT_QUERIES=1 -w /repo web php update.php 2>&1 \
  | grep -oE 'mysqli_[a-z_]+\(\): .* in /[^ ]+ on line [0-9]+' \
  | sed -E 's#^(.*) in /.*/([^/]+) on line ([0-9]+)$#\2:\3 | Warning: \1\t(seen at: update.php)#' \
  >> "$raw"

sort -u "$raw" -o "$raw"

{
  cat <<'HEADER'
# Queries that fail when mysqli error reporting is on.
#
# Generated by tests/query-audit.sh, the only thing that runs the stack with
# MB_REPORT_QUERIES=1. Each entry is source location, the mysqli error, and
# which pass reached it.
#
# This is a Phase 3 worklist, not a test baseline. The app fires ~1300
# unchecked queries and swallows every failure, so each of these has been
# broken in silence -- most of them since 2003, since the columns they name
# have never existed in db.sql.
#
# Covers only the smoke crawl's reachable surface plus the tick. It is a floor
# on the number of broken queries, not a total.
#
# The list should only ever SHRINK. Regenerate with: bash tests/query-audit.sh
HEADER
  cat "$raw"
} > "$OUT"

count=$(grep -cv '^#' "$OUT")
echo
echo "$OUT lists $count distinct failing quer(y/ies)."
